replicaCount: 2

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

service:
  type: NodePort    # <-- Change from ClusterIP to NodePort for browser testing
  port: 80
  nodePort: 30080   # Optional fixed port for Minikube

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: nginx-dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []  # You can add TLS config if needed
